<?php	$parametros = $_SERVER['QUERY_STRING'];		//$nomedoarquivo,$remetente_atual,$email_atual,$dir_orig,$dir_dest,$prog,$gravar	
	//$list_par = split("&", $parametros); // *** split() -- Obsoleta ***;	$list_par = explode("&", $parametros);	$qt = count($list_par);	
	for($i=0;$i<$qt;$i++)	{		$tam = strlen($list_par[$i]);		$pos = stripos($list_par[$i], "=");		$list_par[$i] = substr($list_par[$i],$pos+1);	}	
	$nomedoarquivo = $list_par[0];	$remetente_atual = rawurldecode($list_par[1]);	$email_atual = $list_par[2];	$dir_orig = $list_par[3];	$dir_dest = $list_par[4];	$prog = $list_par[5];	$gravar = $list_par[6];	
	$sobrescrever = $_POST['sobrescrever'];
	if($gravar!='I') { $gravar = $sobrescrever; }
	// Lendo Título ...	$filetorneio = $dir_orig . $nomedoarquivo;	$filetorneio2 = $dir_dest . $nomedoarquivo;		$barra = "\/";	$barra_barra = $barra.$barra;	// "\\\\";	$arq_orig = str_replace($barra, $barra_barra, $filetorneio);	$arq_dest = str_replace($barra, $barra_barra, $filetorneio2);	$filetorneio = $arq_orig;	$filetorneio2 = $arq_dest;		//$filetorneio  = '../TorneiosVG/arquivos/9 ano FEM.vegx';	//$filetorneio2 = '../TorneiosVG/9 ano FEM.vegx';		$filetorneio  = str_replace("%20", " ", $filetorneio);	$filetorneio2 = str_replace("%20", " ", $filetorneio2);		//echo '<br>' . $arq_orig . '<br>' . $arq_dest . '<br>';//exit;	//echo '<br>' . $filetorneio . '<br>' . $filetorneio2 . '<br>';//exit;			// ****************************** Alterar p/ VG ******************************************			//$link = "../TorneiosVG/Copa_Brasil_2019-Regional_Sudeste_FBXDV.vegx"; 			$link = $filetorneio;			//$xml = simplexml_load_file($link);			//$TituloTorneio = utf8_decode($xml->Name);									$doc = new DOMDocument();			//$doc->load('file.xml');			$doc->load($link);			//echo 'Version: ' . $doc->xmlVersion . "\n";   // Like '1.0', you can modify this			//echo 'Encoding: ' . $doc->xmlEncoding . "\n"; // Like 'ISO-8859-1', readonly			if($doc->xmlEncoding!='UTF-8') { echo $doc->xmlEncoding . '<br><br>';}						$file = $link;	//"../config/conexao_ca.cfg";			$fh = fopen($file, 'r');			$conteudo = fread($fh, filesize($file));			if($doc->xmlEncoding!=='UTF-8') {$conteudo=utf8_encode($conteudo);}			//print_r( simplexml_load_string($conteudo) );			//exit;						//$xml = simplexml_load_file($link);	// -> Tournament;			$xml = simplexml_load_string($conteudo);	// -> Tournament;			$TituloTorneio = utf8_decode($xml->Name);			//carrega o arquivo XML e retornando um Array							// ****************************** Alterarp/ VG  ******************************************
	// Lendo String de conexão	$file = "../config/conexao_ca.cfg";	$fh = fopen($file, 'r');	$conteudo = explode("*", fread($fh, filesize($file)));	$strconexao = trim($conteudo[0]);	$codificacao = trim($conteudo[1]);	fclose($fh);	//echo "<option value=''> ******* $strconexao - $resultado *********</option>";	$conexao=pg_connect($strconexao) or die("erro na conexão2");
	$TituloTorneio=utf8_encode($TituloTorneio);	$SubTituloTorneio=utf8_encode($SubTituloTorneio);										// *********** VG ????? **********	//$TituloTorneio = $TituloTorneio . '(' . $SubTituloTorneio . ')';
	$status='A';	$DataRec=Date('Y/m/d');		//$arq_orig = str_replace("\", "\\", $dir_orig . $nomedoarquivo);	$barra = "\/";	$barra_barra = $barra.$barra;	// "\\\\";		//$arq_orig = str_replace(" ", "\ ", str_replace($barra, $barra_barra, $dir_orig . $nomedoarquivo));	//$arq_dest = str_replace(" ", "\ ", str_replace($barra, $barra_barra, $dir_dest . $nomedoarquivo));		//$target = str_replace($barra, $barra_barra, $target   . $nomedoarquivo);	$arq_orig = str_replace($barra, $barra_barra, $dir_orig . $nomedoarquivo);	$arq_dest = str_replace($barra, $barra_barra, $dir_dest . $nomedoarquivo);		$arq_orig = str_replace("%20", " ", $arq_orig);	$arq_dest = str_replace("%20", " ", $arq_dest);		//echo '<br>' . $arq_orig . '<br>' . $arq_dest . '<br>';exit;		switch ($gravar)	{		case 'I':			//echo "case I";exit;			$sql = pg_query($conexao,"INSERT INTO torneios (nome,arquivo,remetente,email,prog,data_rec,status) VALUES ('$TituloTorneio','$nomedoarquivo','$remetente_atual','$email_atual','$prog','$DataRec','$status')") or die("erro no encerramento de INSERT");			//pg_close($conexao) or die("erro no encerramento da conexão");			//echo "$TituloTorneio - $nomedoarquivo - $remetente_atual - $email_atual - $prog - $DataRec - $status - executou insert?";//exit;						//if (copy($dir_orig . $nomedoarquivo, $dir_dest . $nomedoarquivo)) str_replace(" ", "\ ", $image_url			if (copy($arq_orig, $arq_dest))				{					//unlink($dir_orig . $nomedoarquivo);					unlink($arq_orig);				}			else				{					echo "falha ao copiar $file...\n$dir_orig . $nomedoarquivo\n$dir_dest . $nomedoarquivo";				}			break;
		case 'U':			//echo "case U";exit;			$sql = pg_query($conexao,"UPDATE torneios SET nome='$TituloTorneio',remetente='$remetente_atual',email='$email_atual',prog='$prog',data_rec='$DataRec',status='$status' WHERE arquivo='$nomedoarquivo'") or die("erro de UPDATE");						//if (copy($dir_orig . $nomedoarquivo, $dir_dest . $nomedoarquivo))			if (copy($arq_orig, $arq_dest))				{					//unlink($dir_orig . $nomedoarquivo);					unlink($arq_orig);				}			else				{					echo "falha ao copiar $file...\n";				}			break;
		case 'N':			echo "case N";			echo "<SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript'>history.go(-2);</script>";exit;			break;
		default:			echo "<b><u>Falha Inesperada</u></b>!!! <b><u>Informe a pclevybr@gmail.com</u></b>!!";exit;	}
	$sql = pg_query($conexao,"SELECT * FROM torneios WHERE arquivo='$nomedoarquivo'") or die("erro de SELECT");	$TituloTorneio = utf8_decode(trim(pg_result($sql,0,'nome')));	$torneio_reg = trim(pg_result($sql,0,'reg'));	$remetente = utf8_decode(trim(pg_result($sql,0,'remetente')));
	pg_close($conexao) or die("erro no encerramento da conexão");
 echo     '<center>       <font size="3"><b>AI Paulo C. Levy<b></font><br>       <font size="4">Arquivo do Árbitro</font><br>       <font size="3"><b>Consulta a Torneios Vega</b></font><br>       <br>       <font size="3"><b><u>Recepção de Torneios</u></b></font><br><br><br>     ';  echo "<br>	      <font size='3'>Título do Torneio: <font size='+1'>$TituloTorneio</font>				<br>	      <font size='3'>Nome do Arquivo: <font size='+1'>$nomedoarquivo</font>				<br>	      <font size='3'>Registro: <font size='+1'>$torneio_reg</font>				<br>	      <font size='3'>Remetente: <font size='+1'>$remetente</font>				<br>";
//echo "<meta http-equiv='refresh' content='0;URL=../php/LerArquivoSM.php?arq=$nomedoarquivo&DtRec=$DataRec&Remetente=$remetente_atual'>";//echo "<meta http-equiv='refresh' content='0;URL=../php/LerArquivoSM.php?arq=$nomedoarquivo&dtrec=$DataRec&remetente=$remetente_atual&torneio_reg=$torneio_reg&janela=1'>";	//echo "<meta http-equiv='refresh' content='0;URL=index.php?page=torneio.php&torneio_reg=$torneio_reg'>";  // ************ VG ****************	echo "<meta http-equiv='refresh' content='0;URL=../php/LerArquivoVG.php?arq=$nomedoarquivo&DtRec=$DataRec&Remetente=$remetente_atual'>"; // *** VG ***
	exit;
?>